// import { Grid } from "@mui/material";
import { Metadata } from "next";
import React from "react";
import { AuthProvider } from "@/context/AuthContext";
export const metadata: Metadata = {
  title: "Mini Jobs Board",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body>
        <main>
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
};
export default Layout;
